# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Genomic Ruminations
author: "Cristian Groza"
email: "cristian.groza@mail.mcgill.ca"
description: "This page exists just in case I ever think of something original."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https/cgroza.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: groza_cristian
github_username:  cgroza

# Build settings
markdown: kramdown
theme: minima
minima:
  skin: dark

show_excerpts: false

future: true

plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
header_pages:
  - index.md
  - pubs.md
  - about.md

plugins: ['jekyll/scholar']

scholar:
  style: genome-biology-and-evolution
  bibliography_template: "{{ reference | replace_first: 'Groza C', '<b>Groza C</b>' }}"
